sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t anubhav2381/tests ./client

script:
  - docker run anubhav2381/tests npm test -- --covergae

after_success:
  - docker build -t anubhav2381/multi-container-client ./client
  - docker build -t anubhav2381/multi-container-server ./server
  - docker build -t anubhav2381/multi-container-worker ./worker
  - docker build -t anubhav2381/multi-container-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push anubhav2381/multi-container-client
  - docker push anubhav2381/multi-container-server
  - docker push anubhav2381/multi-container-worker
  - dcoker push anubhav2381/multi-container-nginx